### ISSUE TITLE
There is no separation of concerns in the `touchFloatingPoint` function

### ISSUE THREAD

**Issue by fadi-botros** [nadawoud/Calculator#2]
https://github.com/nadawoud/Calculator/blob/5cdecb7e556e0e23b571133bdc332f81cfa2d185/Calculator/ViewController.swift#L30-L40

I think that it should be better to put the code that handles the presses in model class. This could be considered an application logic, not UI. {But I think separate model, not the same `CalculatorBrain`}

**Comment by nadawoud** [comment]
This function adds a floating point to `display lable` when the floating point button is touched. This is completely UI and has nothing to do with the logic.
